### ISSUE TITLE
svg-paths: dragging handles can cause `TypeError`s

### ISSUE THREAD

**Issue by wbobeirne** [narendrasss/NotANumber#84]
```
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at page-83e5b7ebd6eed009.js:1:6797
    at onPan (page-83e5b7ebd6eed009.js:1:7590)
    at updatePoint (8143-a0d72c3a219c846a.js:17:91123)
    at Object.process (8143-a0d72c3a219c846a.js:17:80575)
    at v (8143-a0d72c3a219c846a.js:17:80864)
    at Array.forEach (<anonymous>)
    at y (8143-a0d72c3a219c846a.js:17:80966)
```

I got this on https://www.nan.fyi/svg-paths/bezier-curves dragging around the handles in the Bezier Curves section

```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at page-e347324c9032a57e.js:1:29154
    at onPan (page-e347324c9032a57e.js:1:6790)
    at updatePoint (8143-a0d72c3a219c846a.js:17:91123)
    at Object.process (8143-a0d72c3a219c846a.js:17:80575)
    at v (8143-a0d72c3a219c846a.js:17:80864)
    at Array.forEach (<anonymous>)
    at y (8143-a0d72c3a219c846a.js:17:80966)
```

I got this on https://www.nan.fyi/svg-paths/arcs by dragging around the horizontal and vertical handles in the Arcs section.

Sorry for the minified stack traces!

**Comment by narendrasss** [comment]
You're totally right! I remember getting this while testing but I totally forgot to fix it before it went live. Fixing now.

**Comment by narendrasss** [comment]
Fix is deployed!
